// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:ses/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-a5tlu0E2yuMJVadoyUE8Y_JsDwjGrr0',
    appId: '1:661792780030:web:206013af8389e8b4c2bfaf',
    messagingSenderId: '661792780030',
    projectId: 'sesmusic-e02aa',
    authDomain: 'sesmusic-e02aa.firebaseapp.com',
    storageBucket: 'sesmusic-e02aa.firebasestorage.app',
    measurementId: 'G-632TDJXK79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcuNLQlk6d4k6kc78h42u-0Sw5Kk2zVm0',
    appId: '1:661792780030:android:cf3cb2efad543d19c2bfaf',
    messagingSenderId: '661792780030',
    projectId: 'sesmusic-e02aa',
    storageBucket: 'sesmusic-e02aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmreQnD-ULoA-vgrGsEv5TMy1oYfOg69I',
    appId: '1:661792780030:ios:21fafacb52d2764cc2bfaf',
    messagingSenderId: '661792780030',
    projectId: 'sesmusic-e02aa',
    storageBucket: 'sesmusic-e02aa.firebasestorage.app',
    iosClientId: '661792780030-27b17v8qcouujvmj61ckfdb8cl1ifbup.apps.googleusercontent.com',
    iosBundleId: 'com.example.ses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmreQnD-ULoA-vgrGsEv5TMy1oYfOg69I',
    appId: '1:661792780030:ios:21fafacb52d2764cc2bfaf',
    messagingSenderId: '661792780030',
    projectId: 'sesmusic-e02aa',
    storageBucket: 'sesmusic-e02aa.firebasestorage.app',
    iosClientId: '661792780030-27b17v8qcouujvmj61ckfdb8cl1ifbup.apps.googleusercontent.com',
    iosBundleId: 'com.example.ses',
  );
}
